#1. Determinan dari matrik indentitas yg menghasilkan 1

In [1]:
import numpy as np
A= np.array ([[1,0],[0,1]])
determinan = np.linalg.det(A)
print (A,"\n")
print("determinan matrik adalah  identitas ordo 2x2 adalah:", int (determinan))

B = np.array ([[1,0,0],[0,1,0],[0,0,1]])
determinan = np.linalg.det(B)
print (B,"\n")
print("determinan matrik identitas ordo 3x3 adalah:", int (determinan))

[[1 0]
 [0 1]] 

determinan matrik adalah  identitas ordo 2x2 adalah: 1
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

determinan matrik identitas ordo 3x3 adalah: 1


#2. mendefinisikan sebuah matriks 3x3 dengan elemen-elemennya. Matriks ini kemudian disimpan dalam variabel c dan D

In [2]:
import numpy as np
c= np.array ([[1,2,1],[3,1,2],[2,1,2]])
determinan = np.linalg.det(c)
print (c,"\n")
print("determinan matrik adalah:", int (determinan))

D = np.array ([[3,1,2],[1,2,1],[2,1,2]])
determinan = np.linalg.det(D)
print (D,"\n")
print("determinan matrik jika diubah letak barisnya adalah:", int (determinan))

[[1 2 1]
 [3 1 2]
 [2 1 2]] 

determinan matrik adalah: -3
[[3 1 2]
 [1 2 1]
 [2 1 2]] 

determinan matrik jika diubah letak barisnya adalah: 3


#3.

In [3]:
import numpy as np
E= np.array ([[1,2,1],[2,4,2],[2,1,2]])
determinan = np.linalg.det(E)
print (E,"\n")
print("determinan matrik jika diubah letak barisnya adalah:", int (determinan))

[[1 2 1]
 [2 4 2]
 [2 1 2]] 

determinan matrik jika diubah letak barisnya adalah: 0


In [4]:
import numpy as np
G= np.array ([[6,2,4],[2,4,2],[4,2,4]])
determinan = np.linalg.det(G)
print (G,"\n")
print("determinan matrik adalah:", int (determinan))

[[6 2 4]
 [2 4 2]
 [4 2 4]] 

determinan matrik adalah: 24


#4. jika terdpat matrik yg menghasilkan determinan "x", dan membuat matrik baru dengan kelipatan"y". maka jika "x" dikaikan "y" maka hasilnya determinan dr matrik baru tsb

In [5]:
import numpy as np
A=  np.array([[3,4],[2,1]])
determinan = np.linalg.det(A)
print (A,"\n")
print("determinan dari matrik A adalah:", int (determinan))

H = np.array ([[6,8],[4,2]])
determinan_H = np.linalg.det(H)
print (H,"\n")
print("determinan dari matrik H adalah:", int(determinan_H.round()))

[[3 4]
 [2 1]] 

determinan dari matrik A adalah: -5
[[6 8]
 [4 2]] 

determinan dari matrik H adalah: -20


#5.

In [6]:
import numpy as np
T = 2
A= np.array ([[3,4],[2,1]])
determinan = np.linalg.det(A)
hasil = determinan *2
print (A,"\n")
print("determinan dari matrik A adalah:", int (hasil.round()))

I= np.array ([[3*T,4*T],[2,1]])
determinan_I = np.linalg.det(I)
print (I,"\n")
print("determinan dari matrik I adalah:", int(determinan_I.round()))

[[3 4]
 [2 1]] 

determinan dari matrik A adalah: -10
[[6 8]
 [2 1]] 

determinan dari matrik I adalah: -10


#6. Det(A2)= det (B)+ det (A)
sehingga det  (a2)=(-5)+(-3)

In [7]:
import numpy as np
A2 = np.array ([[7,5],[2,1]])
determinan = np.linalg.det(A2)
print (A2,"\n")
print("determinan dari matrik A2 adalah:", int (determinan.round()))

A = np.array ([[4,1],[2,1]])
determinan_A = np.linalg.det(A)
print (A,"\n")
print("determinan dari matrik A adalah:", int (determinan_A.round()))

B = np.array ([[3,4],[2,1]])
determinan_B = np.linalg.det(B)
print (B,"\n")
print("determinan dari matrik B adalah:", int (determinan_B.round()))

[[7 5]
 [2 1]] 

determinan dari matrik A2 adalah: -3
[[4 1]
 [2 1]] 

determinan dari matrik A adalah: 2
[[3 4]
 [2 1]] 

determinan dari matrik B adalah: -5


# 7.

In [8]:
import numpy as np
A = np.array ([[1,3,2],[0,2,2],[0,0,1]])
determinan = np.linalg.det(A)
print (A,"\n")
print("determinan matrik adalah:", int (determinan))

[[1 3 2]
 [0 2 2]
 [0 0 1]] 

determinan matrik adalah: 2


In [9]:
# tidak boleh sama
import numpy as np
A = np.array ([[1,5,3],[6,4,2],[0,0,1]])
determinan = np.linalg.det(A)
print (A,"\n")
print("determinan matrik adalah:", int (determinan))

[[1 5 3]
 [6 4 2]
 [0 0 1]] 

determinan matrik adalah: -25
