# Tugas 3

1. Matrik Inves
2. sifat-sifat matriks inves
3. mencari invers dengan eliminasi gaus jordan
4. solusi sistem persamaan linear dengan matrik inver
5. membuat soal persamaan linear 6 variabel

## 1. pengertian invers matrik
Invers matriks adalah kebalikan (invers) dari sebuah matriks yang apabila matriks tersebut dikalikan dengan inversnya, akan menjadi matriks identitas. Invers matriks dilambangkan dengan A-1. Suatu matriks dikatakan memiliki invers jika determinan dari matriks tersebut tidak sama dengan nol

## 2. Sifat invers matriks
adalah sifat yang berlaku untuk matriks yang merupakan kebalikan dari matriks asal. Invers matriks dapat ditulis dengan simbol A−1, yang berarti matriks yang jika dikalikan dengan matriks A, hasilnya adalah matriks identitas I. Matriks identitas adalah matriks yang memiliki angka 1 di diagonal utama dan angka 0 di luar diagonal utama.Beberapa sifat-sifat invers matriks adalah sebagai berikut:

1. Invers matriks hanya ada untuk matriks persegi, yaitu matriks yang memiliki jumlah baris dan kolom yang sama.
2. Invers matriks hanya ada untuk matriks nonsingular, yaitu matriks yang memiliki determinan tidak sama dengan nol. Determinan adalah nilai yang dapat dihitung dari unsur-unsur suatu matriks persegi.
3. Invers matriks adalah tunggal, yaitu tidak ada lebih dari satu matriks yang dapat menjadi invers dari suatu matriks. Jika B dan C keduanya adalah invers dari A, maka B=C.
4. Invers dari invers suatu matriks adalah matriks itu sendiri. Jika B adalah invers dari A, maka invers dari B adalah A. Dapat ditulis (A^−1)^−1 = A.
5. Invers dari hasil kali dua atau lebih matriks adalah hasil kali invers-inversnya dalam urutan terbalik. Jika A dan B keduanya nonsingular, maka (AB)^−1 = B^−1 A^−1.
6. Invers dari transpos suatu matriks adalah transpos dari inversnya. Transpos adalah operasi menukar baris dan kolom suatu matriks. Jika A nonsingular, maka (A^T)^−1 = (A^−1)^T.



## 3. mencari invers dengan eliminasi gaus jordan
Untuk mencari invers dari sebuah matriks menggunakan metode eliminasi Gauss-Jordan, langkah-langkahnya adalah sebagai berikut:

Misalkan kita memiliki matriks
A yang ingin kita inverskan dengan ukuran n×n. Langkah-langkahnya adalah sebagai berikut:
1. Gabungkan matriks A dengan matriks identitas I , dengan ukuran yang sama.Ini akan menjadi matriks gabungan [A∣I].

2. Gunakan operasi baris elementer (OBE) untuk mentransformasikan matriks A menjadi matriks identitas I. Ini dilakukan dengan cara membuat elemen diagonal utama dari matriks A menjadi 1 dan membuat semua elemen di atas dan di bawahnya menjadi 0.

3. Setelah matriks A menjadi matriks identitas, matriks yang berada di sebelah kanan I akan menjadi invers dari matriks A

## 4. solusi sistem persamaan linear dengan matrik inver
Untuk menyelesaikan sistem persamaan linear menggunakan matriks invers, kita bisa menggunakan hubungan:

1. X=A −1B

Di mana:
* A adalah matriks koefisien dari sistem persamaan linear.
* B adalah matriks kolom dari konstanta pada sisi kanan sistem persamaan linear.
* X adalah matriks kolom dari variabel yang kita cari.
Langkah-langkahnya adalah sebagai berikut:

  1. Hitung invers dari matriks koefisien A inv, yaitu A−1
  2. Kalikan 1 A inv −1 dengan matriks kolom B untuk mendapatkan matriks kolom X,
  3. Matriks kolom X akan berisi solusi untuk sistem persamaan linear. Berikut ini adalah algoritma umum dalam pseudocode:

## 5. membuat soal persamaan linear 6 variabel
Solusi dari sistem persamaan tersebut adalah:
x = 1, y = 2, z = 3, w = 4, u = 5, v = 6
* Sistem persamaan ini dapat diselesaikan dengan metode eliminasi atau substitusi. Pertama, kita perlu mengatur persamaan tersebut dalam bentuk matriks. Kemudian, kita dapat menggunakan metode eliminasi untuk mengurangi jumlah variabel dalam setiap persamaan. Setelah itu, kita dapat menyelesaikan persamaan yang tersisa untuk menemukan nilai dari setiap variabel. Dalam hal ini, solusi dari sistem persamaan tersebut adalah x = 1, y = 2, z = 3, w = 4, u = 5, v = 6.
* Untuk menyelesaikan sistem persamaan linear dengan 6 variabel seperti yang diberikan, langkah-langkahnya adalah sebagai berikut:

1. Ubah sistem persamaan ke dalam bentuk matriks augmented:

  $\begin{bmatrix} 2 & 3 & -4 & 5 & 6 & -7 & | & 10 \\ 3 & -5 & 4 & -5 & 6 & 7 & | & 30 \\ 5 & -5 & 4 & -5 & -6 & 7 & | & 30 \\ 6 & 0 & 3 & 2 & -7 & 6 & | & 40 \\ 6 & 6 & 5 & 4 & 3 & 2 & | & 50 \end{bmatrix}$

2. Gunakan operasi baris elementer untuk menyederhanakan matriks menjadi bentuk eselon tereduksi.

3. Setelah matriks dalam bentuk eselon tereduksi, kita dapat menentukan nilai variabel dengan mengubah matriks tersebut kembali menjadi sistem persamaan.

4. Dengan menggantikan nilai variabel yang ditemukan ke dalam sistem persamaan asli, kita dapat memverifikasi solusi yang ditemukan.

Dengan mengikuti langkah-langkah di atas, kita dapat menemukan solusi dari sistem persamaan linear dengan 6 variabel yang diberikan.

In [1]:
import numpy as np

A = np.array([[2, 3],
              [3, 1]])

B = np.array([[1, 0],
              [0, 1]])

inv_A = np.linalg.inv(A)
inv_B = np.linalg.inv(B)

C = np.dot(A, B)

print("Invers dari matriks A:")
print(inv_A)
print("\nInvers dari matriks B:")
print(inv_B)
print("\nHasil perkalian invers A dengan B:")
print(C)


Invers dari matriks A:
[[-0.14285714  0.42857143]
 [ 0.42857143 -0.28571429]]

Invers dari matriks B:
[[1. 0.]
 [0. 1.]]

Hasil perkalian invers A dengan B:
[[2 3]
 [3 1]]
