In [1]:
#contohnya
import numpy as np
a = np.array([[2,3,1],[0,5,2]])
print('a=' ,a)
print()
b = np.array([[-2,5,0],[-1,2,-3]])
print('b=' ,b)
print()
c = np.array([[4,1,3],[1,5,7]])
print('c=' ,c)
print()

a= [[2 3 1]
 [0 5 2]]

b= [[-2  5  0]
 [-1  2 -3]]

c= [[4 1 3]
 [1 5 7]]



# TUGASNYA
  # NO TUGAS NO KELAS
 - Berikan penjelasan tentang apa itu matriks
 - Operasi matriks
 - penjumlahan, perkalian, pengurangan
 - transpose matriks
 - Buat program untuk mengalikan matrik A dan B tidak menggunakan a'
 - saya disuruh membuat matriks A dan B dengan ordo 3X3 dan matriks C dengan ordo $3\times 2$

* 1.Penjelasan tentang Matriks:

  Matriks adalah tabel berisi elemen-elemen yang diatur dalam baris dan kolom. Setiap elemen dalam matriks dapat diidentifikasi oleh posisi baris dan kolomnya. Misalnya, matriks A dengan ordo m x n memiliki m baris dan n kolom.

  Secara umum
  Matriks digunakan secara luas dalam berbagai bidang, termasuk matematika, ilmu komputer, fisika, ekonomi, dan banyak lagi. Matriks sangat berguna untuk merepresentasikan data dalam bentuk yang terstruktur dan dapat diterapkan dalam berbagai operasi matematika seperti penjumlahan, pengurangan, perkalian, dan operasi lainnya

In [2]:
import numpy as np
a = np.array([[2,4,1],[0,5,7],[3,8,6]])#matrik 3x3
b = np.array([[-2,6,0],[4,1,-3],[2,7,5]])#matrik 3x3
c = np.array([[3,1],[-2,5],[0,7]])#matrik 3x2
d = np.array([[1,4],[6,-1],[2,0]])#matrik 3x2
print('a+b=' ,a@b)

a+b= [[14 23 -7]
 [34 54 20]
 [38 68  6]]


In [3]:
import numpy as np
A = np.array([[1, 3, 3],[2, 1, 9],[2, 4, 7]])
B = np.array([[1,6,3],[2,8,7],[3,9,5]]) #3x3
C = np.array([[2,4],[5,2],[6,7]]) #3x2
D = np.array([[3,7,5],[1,4,8],[2,4,5]])
E = A+B #penjumlahan
F = 2*A #Skala
G = A@C #perkalian
H = B@C
I = A@H
J = A@B
K = J@C
L = A-B #pengurangan


In [4]:
C_trans = C.transpose()
Z = C_trans@C
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(I)
print('\n')
print(K)
print('\n')
print(L)
print('\n')
print(C_trans)
print(Z)

[[ 2  9  6]
 [ 4  9 16]
 [ 5 13 12]]


[[ 2  6  6]
 [ 4  2 18]
 [ 4  8 14]]


[[35 31]
 [63 73]
 [66 65]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 551  451]
 [ 915  732]
 [1011  821]]


[[ 0 -3  0]
 [ 0 -7  2]
 [-1 -5  2]]


[[2 5 6]
 [4 2 7]]
[[65 60]
 [60 69]]


In [5]:
# Membuat matriks A dengan ordo 3x3
A = [[4,8,1],
     [9,0,2],
     [2,5,-3]]

# Membuat matriks B dengan ordo 3x3
B = [[3,8,2],
     [5,7,-2],
     [6,3,7]]

# Membuat matriks C dengan ordo 3x2
C = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

# Membuat matriks D dengan ordo 3x2
D = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]


# Mengalikan matriks A dan B
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

# Menampilkan hasil perkalian
print("Hasil perkalian matriks A dan B:")
for row in C:
    print(row)


Hasil perkalian matriks A dan B:
[58, 91, -1]
[39, 78, 32]
[13, 42, -27]
